#! /bin/bash

lines=$(cut -f1,11 -d" " $1 | grep '"-"' | cut -f1 -d" " | wc -l);
echo $lines;
for i in `cut -f1,11 -d" " $1 | grep '"-"' | cut -f1 -d" " | sort -t" " -k1 | uniq -c | sort -r | head -n 10`; 
do if [[ $i =~ ^[0-9]+$ ]]; then 

printf "$i - $(echo "scale=4;$i*100/$lines" | bc -l) %%";
else printf " - $i \n"; fi 
done

